travis:
  secure:
    BINSTAR_TOKEN: B0xLKieLvZXGfcRlksmmhba7V/xoKokduLsd2S4RBNfL7ttsj0UWxNHy6wHl9fv+Z5ZN2qOFV7vbFwr+m4dWrFaL7LIjFVbA/DK2P0MXPxT1KKAbl3PXo49KeF6cO8HD3bXllg9tmFZsbEqntes5uKP0yaZyPfru2N41w8Wd6SQ5OzFcLgpAUrJvpch1ySRqbRFAufx9ws5g/YCAmPXq//K4j3tp5AnGn3igJTYAhCXQLLzhhiCpXZMgCy1vi4lLbIS1/cO4mgTQR14lTNGrsdjkI+uW/08WXX8DVWjM6oi7lCuW2PTlK1tqjHe56NSglxQM8Qs4KyhuDt4ox8//4sAbLeKX654XUEhs4JD0R8ahcRHYH9wtEPgfjEw+Eqb3wKXXxKYzgghfPECbAyNGBxOJwOYcezGr7l4g3b4fzvFFF5dE3HE+3Idt3bycnvV5YqLgwFVrn2G7u1yPFMHukzQF91uJmJGd4PueACbu6johj3BHpzzdLzrj6DOrQwOnDfBbA9YhErtrAwnBQyT3ccWxZvWNLLbQK//z1qX0JjdU3p8h1stJK2nes23NjjpmndzWoBaOFQmO+mFDM3rixIBR2bYxqY77At74pjc9VwOf5QOrM/oM2qSxrJ5esc1Py0hFvb5nfB7uCIAOFqOpy7406gWOapl/I20acPcslw4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
